### PR TITLE
Update BasicUserInput

### PR DESCRIPTION
**Pull request by devnarayanp02**

### CODE REVIEW

**Comment by devnarayanp02** [comment]
hey, can you please add 'hacktoberfest-accepted' lable to my pull request ?

**Comment by NemaPy** [comment]
Hi,

Sorry I'm very new to Github. How do I do this?

**Comment by devnarayanp02** [comment]
> hey, can you please add 'hacktoberfest-accepted' lable to my pull request ?

https://github.com/NemaPy/Beginner-Projects/pull/3#issuecomment-703119213

go to this link and click on labels and type 'hacktoberfest-accepted' and create label,
i don't  know this will be need to labeled or not but i saw this label in another pull request. so if you can do it please label to my pull request.

**Comment by devnarayanp02** [comment]
> > hey, can you please add 'hacktoberfest-accepted' lable to my pull request ?
> 
> [#3 (comment)](https://github.com/NemaPy/Beginner-Projects/pull/3#issuecomment-703119213)
> 
> go to this link and click on labels and type 'hacktoberfest-accepted' and create label,
> i don't know this will be need to labeled or not but i saw this label in another pull request. so if you can do it please label to my pull request.

https://github.com/NemaPy/Beginner-Projects/pull/3#issuecomment-703119213

**Comment by devnarayanp02** [comment]
i can't see the link, but i was paste link, ok don't do anything, thankyou.

**Pull request merged**
